import {
  ClassGroup,
  Student,
  DailyReport,
  ClassActivity,
  MediaItem,
  RegistrationApplication,
  Announcement,
  MealMenuItem,
  Teacher,
  MonthlyDue,
} from "../types";

export const INITIAL_CLASSES: ClassGroup[] = [
  {
    id: 1,
    name: "1. Sınıf: Minik Tırtıllar",
    shortName: "Minik Tırtıllar",
    ageGroup: "1 - 2 Yaş (Oyun & Keşif)",
    teacher: "Merve Güneş",
    teacherTitle: "Bebek & Erken Çocukluk Gelişim Uzmanı",
    room: "Papatya Salonu (Zemin Kat)",
    capacity: 10,
    color: "from-amber-400 to-orange-400",
    bgGradient: "bg-amber-50 border-amber-200",
    accentColor: "#F59E0B",
    icon: "🐛",
    description: "İlk adımlar, duyusal oyun havuzları, sevgi dolu bakım ve güvenli bağlanma odaklı sıcacık bir yuva.",
    scheduleHighlights: ["Duyusal Keşif Saati", "Şarkılı Ritim Oyunları", "Yumuşak Minder Parkuru", "Açık Hava Çim Saati"],
  },
  {
    id: 2,
    name: "2. Sınıf: Sevimli Kelebekler",
    shortName: "Sevimli Kelebekler",
    ageGroup: "2 - 3 Yaş (Dil & Hareket)",
    teacher: "Zeynep Çelik",
    teacherTitle: "Çocuk Gelişimi & Montessori Eğitmeni",
    room: "Gökkuşağı Sınıfı (1. Kat)",
    capacity: 12,
    color: "from-pink-400 to-rose-400",
    bgGradient: "bg-pink-50 border-pink-200",
    accentColor: "#EC4899",
    icon: "🦋",
    description: "Sözcüklerin zenginleştiği, parmak boyası ve özgür hareketlerle kendi benliğini keşfettiği renkli bir dünya.",
    scheduleHighlights: ["Parmak Boyası Atölyesi", "Hikaye Masal Çemberi", "Müzikli Jimnastik", "Bahçede Kum Oyunu"],
  },
  {
    id: 3,
    name: "3. Sınıf: Neşeli Sincaplar",
    shortName: "Neşeli Sincaplar",
    ageGroup: "3 - 4 Yaş (Sosyalleşme & Doğa)",
    teacher: "Elif Doğan",
    teacherTitle: "Okul Öncesi Öğretmeni & Doğa Pedagoğu",
    room: "Orman Atölyesi (1. Kat)",
    capacity: 14,
    color: "from-emerald-400 to-teal-500",
    bgGradient: "bg-emerald-50 border-emerald-200",
    accentColor: "#10B981",
    icon: "🐿️",
    description: "Paylaşma, işbirliği, doğayı gözlemleme, tohum ekme ve yaratıcı masal canlandırmalarıyla dolu bir grup.",
    scheduleHighlights: ["Botanik Bahçe Bakımı", "Rol Yapma & Drama", "Bilişsel Eşleştirme Oyunları", "Ahşap Blok İnşası"],
  },
  {
    id: 4,
    name: "4. Sınıf: Minik Mucitler",
    shortName: "Minik Mucitler",
    ageGroup: "4 - 5 Yaş (STEM & Deney)",
    teacher: "Selin Yılmaz",
    teacherTitle: "Okul Öncesi STEM & Zeka Oyunları Eğitmeni",
    room: "Mucitler Laboratuvarı (2. Kat)",
    capacity: 16,
    color: "from-sky-400 to-blue-500",
    bgGradient: "bg-sky-50 border-sky-200",
    accentColor: "#38BDF8",
    icon: "🔬",
    description: "Meraklı sorular, su ve yanardağ deneyleri, İngilizce şarkılar ve kavram gelişiminin zirve yaptığı sınıf.",
    scheduleHighlights: ["Eğlenceli Fen Deneyi", "İngilizce Oyun & Şarkı", "Origami & Seramik", "Minderli Yoga & Esneme"],
  },
  {
    id: 5,
    name: "5. Sınıf: Masal Kahramanları",
    shortName: "Masal Kahramanları",
    ageGroup: "5 - 6 Yaş (Yaratıcı Sanat & Kodlama)",
    teacher: "Gamze Karaca",
    teacherTitle: "Sanat Eğitmeni & Masal Terapisti",
    room: "Sanat & Düşler Odası (2. Kat)",
    capacity: 16,
    color: "from-purple-400 to-indigo-500",
    bgGradient: "bg-purple-50 border-purple-200",
    accentColor: "#8B5CF6",
    icon: "🧙‍♂️",
    description: "Ekranız algoritma oyunları, tiyatro çalışmaları, tuval boyama ve ilkokul öncesi özgüven güçlendirme.",
    scheduleHighlights: ["Kukla & Tiyatro Gösterisi", "Fiziksel Kodlama Matı", "Ritim & Orff Çalgıları", "Satranç Temelleri"],
  },
  {
    id: 6,
    name: "6. Sınıf: Geleceğin Yıldızları",
    shortName: "Geleceğin Yıldızları",
    ageGroup: "6 Yaş (İlkokula Hazırlık & Mezuniyet)",
    teacher: "Ahmet Özdemir",
    teacherTitle: "Kıdemli Okul Öncesi Eğitim Koordinatörü",
    room: "Yıldızlar Salonu (3. Kat)",
    capacity: 18,
    color: "from-amber-500 to-red-500",
    bgGradient: "bg-orange-50 border-orange-200",
    accentColor: "#F97316",
    icon: "⭐",
    description: "Çizgi çalışmaları, ses farkındalığı, temel matematik, sorumluluk bilinci ve görkemli mezuniyet yılı.",
    scheduleHighlights: ["Ses & Çizgi Çalışmaları", "Matematik & Mantık Atölyesi", "Sosyal Sorumluluk Kulübü", "İlkokul Oryantasyonu"],
  },
];

export const INITIAL_STUDENTS: Student[] = [
  // 1. Sınıf
  {
    id: "stu-101",
    classId: 1,
    name: "Ali",
    surname: "Demir",
    studentCode: "MD-101",
    username: "MD-101",
    password: "1234",
    gender: "erkek",
    avatar: "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=150&auto=format&fit=crop&q=80",
    birthDate: "2024-03-12",
    parentName: "Hakan Demir (Baba)",
    parentPhone: "0532 111 22 33",
    parentEmail: "hakan.demir@example.com",
    emergencyContact: "0533 999 88 77 (Anneanne)",
    bloodType: "A Rh+",
    allergies: "Çilek alerjisi var",
    notes: "Uyku öncesi tavşan peluşunu seviyor.",
  },
  {
    id: "stu-102",
    classId: 1,
    name: "Ada",
    surname: "Kaya",
    studentCode: "MD-102",
    username: "MD-102",
    password: "1234",
    gender: "kız",
    avatar: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80",
    birthDate: "2024-05-20",
    parentName: "Selin Kaya (Anne)",
    parentPhone: "0542 333 44 55",
    parentEmail: "selin.kaya@example.com",
    emergencyContact: "0543 222 11 00 (Baba)",
    bloodType: "0 Rh+",
    notes: "Müzikli oyunlarda çok enerjik.",
  },

  // 2. Sınıf
  {
    id: "stu-201",
    classId: 2,
    name: "Can",
    surname: "Yıldız",
    studentCode: "MD-201",
    username: "MD-201",
    password: "1234",
    gender: "erkek",
    avatar: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=150&auto=format&fit=crop&q=80",
    birthDate: "2023-08-15",
    parentName: "Mehmet Yıldız (Baba)",
    parentPhone: "0555 444 55 66",
    parentEmail: "mehmet.yildiz@example.com",
    emergencyContact: "0555 111 33 22 (Anne)",
    bloodType: "B Rh+",
    notes: "Boyama yapmayı çok seviyor.",
  },
  {
    id: "stu-202",
    classId: 2,
    name: "Defne",
    surname: "Aydın",
    studentCode: "MD-202",
    username: "MD-202",
    password: "1234",
    gender: "kız",
    avatar: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=150&auto=format&fit=crop&q=80",
    birthDate: "2023-11-04",
    parentName: "Büşra Aydın (Anne)",
    parentPhone: "0535 777 88 99",
    parentEmail: "busra.aydin@example.com",
    emergencyContact: "0535 666 44 33 (Teyze)",
    bloodType: "AB Rh+",
    allergies: "Laktoz hassasiyeti var (Badem sütü verilebilir)",
  },

  // 3. Sınıf
  {
    id: "stu-301",
    classId: 3,
    name: "Efe",
    surname: "Öztürk",
    studentCode: "MD-301",
    username: "MD-301",
    password: "1234",
    gender: "erkek",
    avatar: "https://images.unsplash.com/photo-1485546246426-74dc88dec4d9?w=150&auto=format&fit=crop&q=80",
    birthDate: "2022-04-10",
    parentName: "Cem Öztürk (Baba)",
    parentPhone: "0536 222 33 44",
    parentEmail: "cem.ozturk@example.com",
    emergencyContact: "0536 888 77 66 (Anne)",
    bloodType: "A Rh-",
    notes: "Bahçede böcek incelemeyi çok seviyor.",
  },
  {
    id: "stu-302",
    classId: 3,
    name: "Zeynep",
    surname: "Arslan",
    studentCode: "MD-302",
    username: "MD-302",
    password: "1234",
    gender: "kız",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    birthDate: "2022-09-22",
    parentName: "Derya Arslan (Anne)",
    parentPhone: "0544 555 66 77",
    parentEmail: "derya.arslan@example.com",
    emergencyContact: "0544 111 22 33 (Baba)",
    bloodType: "0 Rh+",
  },

  // 4. Sınıf
  {
    id: "stu-401",
    classId: 4,
    name: "Kerem",
    surname: "Şahin",
    studentCode: "MD-401",
    username: "MD-401",
    password: "1234",
    gender: "erkek",
    avatar: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&auto=format&fit=crop&q=80",
    birthDate: "2021-02-18",
    parentName: "Murat Şahin (Baba)",
    parentPhone: "0533 777 66 55",
    parentEmail: "murat.sahin@example.com",
    emergencyContact: "0533 111 44 22 (Anne)",
    bloodType: "A Rh+",
    notes: "Legolarla kale yapma ustası.",
  },
  {
    id: "stu-402",
    classId: 4,
    name: "Elif",
    surname: "Koç",
    studentCode: "MD-402",
    username: "MD-402",
    password: "1234",
    gender: "kız",
    avatar: "https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=150&auto=format&fit=crop&q=80",
    birthDate: "2021-07-30",
    parentName: "Nuray Koç (Anne)",
    parentPhone: "0541 888 99 00",
    parentEmail: "nuray.koc@example.com",
    emergencyContact: "0541 333 55 44 (Baba)",
    bloodType: "B Rh+",
  },

  // 5. Sınıf
  {
    id: "stu-501",
    classId: 5,
    name: "Mert",
    surname: "Gül",
    studentCode: "MD-501",
    username: "MD-501",
    password: "1234",
    gender: "erkek",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80",
    birthDate: "2020-03-05",
    parentName: "Oğuz Gül (Baba)",
    parentPhone: "0538 444 33 22",
    parentEmail: "oguz.gul@example.com",
    emergencyContact: "0538 999 11 22 (Anne)",
    bloodType: "0 Rh-",
  },
  {
    id: "stu-502",
    classId: 5,
    name: "Lara",
    surname: "Aksoy",
    studentCode: "MD-502",
    username: "MD-502",
    password: "1234",
    gender: "kız",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    birthDate: "2020-08-14",
    parentName: "Banu Aksoy (Anne)",
    parentPhone: "0537 666 55 44",
    parentEmail: "banu.aksoy@example.com",
    emergencyContact: "0537 222 33 11 (Baba)",
    bloodType: "A Rh+",
    allergies: "Fındık/Fıstık alerjisi var",
  },

  // 6. Sınıf
  {
    id: "stu-601",
    classId: 6,
    name: "Emir",
    surname: "Polat",
    studentCode: "MD-601",
    username: "MD-601",
    password: "1234",
    gender: "erkek",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    birthDate: "2019-01-25",
    parentName: "Kemal Polat (Baba)",
    parentPhone: "0539 333 22 11",
    parentEmail: "kemal.polat@example.com",
    emergencyContact: "0539 777 88 66 (Anne)",
    bloodType: "AB Rh-",
    notes: "Satranç kulübünde şampiyonluk adayı.",
  },
  {
    id: "stu-602",
    classId: 6,
    name: "Beren",
    surname: "Çetin",
    studentCode: "MD-602",
    username: "MD-602",
    password: "1234",
    gender: "kız",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    birthDate: "2019-06-11",
    parentName: "Gülizar Çetin (Anne)",
    parentPhone: "0545 222 11 99",
    parentEmail: "gulizar.cetin@example.com",
    emergencyContact: "0545 444 88 77 (Baba)",
    bloodType: "0 Rh+",
    notes: "Kitap okuma saatlerinde arkadaşlarına hikaye anlatıyor.",
  },
];

export const INITIAL_DAILY_REPORTS: DailyReport[] = [
  {
    id: "rep-101",
    studentId: "stu-101",
    date: "2026-09-16",
    meals: {
      breakfast: "hepsini_yedi",
      lunch: "yarisini_yedi",
      snack: "hepsini_yedi",
      notes: "Öğle yemeğindeki sebze çorbasını çok beğendi.",
    },
    sleep: {
      slept: true,
      durationMinutes: 90,
      notes: "13:00 - 14:30 arası kesintisiz ve huzurlu uyudu.",
    },
    mood: "cok_mutlu",
    activitiesAttended: ["Duyusal Keşif Saati", "Şarkılı Ritim Oyunları"],
    teacherNote: "Ali bugün parmak oyunlarında çok heyecanlıydı. Arkadaşlarına sarılarak gülümsedi. Harika bir gün geçirdi!",
  },
  {
    id: "rep-102",
    studentId: "stu-102",
    date: "2026-09-16",
    meals: {
      breakfast: "hepsini_yedi",
      lunch: "hepsini_yedi",
      snack: "hepsini_yedi",
      notes: "Meyve tabağındaki elmaları neşeyle tüketti.",
    },
    sleep: {
      slept: true,
      durationMinutes: 75,
      notes: "Masal eşliğinde kolayca uykuya daldı.",
    },
    mood: "neseli",
    activitiesAttended: ["Yumuşak Minder Parkuru", "Duyusal Keşif Saati"],
    teacherNote: "Ada bugün jimnastik minderinde dengede durma oyununu büyük bir başarıyla tamamladı.",
  },
  {
    id: "rep-201",
    studentId: "stu-201",
    date: "2026-09-16",
    meals: {
      breakfast: "yarisini_yedi",
      lunch: "hepsini_yedi",
      snack: "hepsini_yedi",
    },
    sleep: {
      slept: true,
      durationMinutes: 80,
    },
    mood: "cok_mutlu",
    activitiesAttended: ["Parmak Boyası Atölyesi", "Hikaye Masal Çemberi"],
    teacherNote: "Can kelebek resmini gökkuşağı renkleriyle boyadı. Sanat çalışmasını panomuza astık!",
  },
  {
    id: "rep-301",
    studentId: "stu-301",
    date: "2026-09-16",
    meals: {
      breakfast: "hepsini_yedi",
      lunch: "hepsini_yedi",
      snack: "hepsini_yedi",
    },
    sleep: {
      slept: true,
      durationMinutes: 60,
    },
    mood: "neseli",
    activitiesAttended: ["Botanik Bahçe Bakımı", "Rol Yapma & Drama"],
    teacherNote: "Efe okul bahçesindeki nane fidanlarını suladı. Doğaya olan ilgisi hepimizi hayran bırakıyor.",
  },
  {
    id: "rep-401",
    studentId: "stu-401",
    date: "2026-09-16",
    meals: {
      breakfast: "hepsini_yedi",
      lunch: "hepsini_yedi",
      snack: "hepsini_yedi",
    },
    sleep: {
      slept: false,
      durationMinutes: 0,
      notes: "Sessiz kitap okuma köşesinde dinlendi.",
    },
    mood: "cok_mutlu",
    activitiesAttended: ["Eğlenceli Fen Deneyi", "İngilizce Oyun"],
    teacherNote: "Kerem volkan deneyi sırasında en önde gözlem yaptı. 'Lava' sözcüğünü hemen öğrendi!",
  },
  {
    id: "rep-501",
    studentId: "stu-501",
    date: "2026-09-16",
    meals: {
      breakfast: "hepsini_yedi",
      lunch: "hepsini_yedi",
      snack: "hepsini_yedi",
    },
    sleep: {
      slept: false,
      durationMinutes: 0,
      notes: "Serbest dinlenme saati uygulandı.",
    },
    mood: "cok_mutlu",
    activitiesAttended: ["Kukla & Tiyatro", "Fiziksel Kodlama Matı"],
    teacherNote: "Mert kodlama matında robot arkadaşını doğru yönergelerle hedefe ulaştırdı. Tebrikler!",
  },
  {
    id: "rep-601",
    studentId: "stu-601",
    date: "2026-09-16",
    meals: {
      breakfast: "hepsini_yedi",
      lunch: "hepsini_yedi",
      snack: "hepsini_yedi",
    },
    sleep: {
      slept: false,
      durationMinutes: 0,
    },
    mood: "cok_mutlu",
    activitiesAttended: ["Ses & Çizgi Çalışmaları", "Matematik & Mantık"],
    teacherNote: "Emir çizgi labirentini hatasız tamamladı. İlkokul odaklanma becerisi çok yüksek seviyede.",
  },
];

export const INITIAL_ACTIVITIES: ClassActivity[] = [
  {
    id: "act-101",
    classId: 1,
    title: "Duyusal Su ve Jöle Oyunları",
    time: "10:30 - 11:15",
    date: "Bugün",
    category: "Oyun",
    description: "Farklı dokulardaki organik nesneleri keşfetme, el kaslarını ve duyu bütünlüğünü güçlendirme.",
    instructor: "Merve Güneş",
  },
  {
    id: "act-102",
    classId: 1,
    title: "Minik Sesler Ritim Atölyesi",
    time: "15:00 - 15:45",
    date: "Bugün",
    category: "Müzik",
    description: "Marakas ve tefler eşliğinde neşeli çocuk şarkıları dinleme ve alkış tutma.",
    instructor: "Merve Güneş",
  },
  {
    id: "act-201",
    classId: 2,
    title: "Gökkuşağı Parmak Boyası",
    time: "10:00 - 11:00",
    date: "Bugün",
    category: "Sanat",
    description: "Büyük kağıtlar üzerinde eller ve süngerlerle renkleri karıştırarak özgür ifade.",
    instructor: "Zeynep Çelik",
  },
  {
    id: "act-202",
    classId: 2,
    title: "Masal Minderi & Hayvan Sesleri",
    time: "14:30 - 15:15",
    date: "Bugün",
    category: "Dil",
    description: "Büyük resimli masal kitabından orman hayvanlarını tanıma ve seslerini taklit etme.",
    instructor: "Zeynep Çelik",
  },
  {
    id: "act-301",
    classId: 3,
    title: "Ekolojik Bahçe ve Tohum Ekimi",
    time: "10:15 - 11:30",
    date: "Bugün",
    category: "Fen & Doğa",
    description: "Bahçemizde kendi minik saksılarımıza domates ve lavanta tohumları ekiyoruz.",
    instructor: "Elif Doğan",
  },
  {
    id: "act-302",
    classId: 3,
    title: "Orff Çalgıları ile Ritim Çemberi",
    time: "15:30 - 16:15",
    date: "Bugün",
    category: "Müzik",
    description: "Ksilofon ve üçgen zillerle ritim kalıpları çıkarma ve takım uyumu.",
    instructor: "Elif Doğan",
  },
  {
    id: "act-401",
    classId: 4,
    title: "Renkli Köpüren Yanardağ Deneyi",
    time: "11:00 - 12:00",
    date: "Bugün",
    category: "Fen & Doğa",
    description: "Karbonat ve sirke tepkimesini güvenli şekilde gözlemleme, kimya merakı.",
    instructor: "Selin Yılmaz",
  },
  {
    id: "act-402",
    classId: 4,
    title: "İngilizce Drama: 'The Little Bear'",
    time: "14:45 - 15:30",
    date: "Bugün",
    category: "Dil",
    description: "İngilizce diyaloglar eşliğinde ayı kostümü ve arkadaşları canlandırması.",
    instructor: "Selin Yılmaz",
  },
  {
    id: "act-501",
    classId: 5,
    title: "Algoritma ve Labirent Matı",
    time: "10:30 - 11:30",
    date: "Bugün",
    category: "Bilişsel & Kodlama",
    description: "Ok yönleri ve komut kartları kullanarak arkadaşını hazineye ulaştırma oyunu.",
    instructor: "Gamze Karaca",
  },
  {
    id: "act-502",
    classId: 5,
    title: "Kil ve Seramik Çömlek Atölyesi",
    time: "15:15 - 16:15",
    date: "Bugün",
    category: "Sanat",
    description: "Doğal seramik çamuru ile sevimli hayvan figürleri ve tabaklar tasarlama.",
    instructor: "Gamze Karaca",
  },
  {
    id: "act-601",
    classId: 6,
    title: "Fonolojik Farkındalık & Ses Avı",
    time: "09:30 - 10:30",
    date: "Bugün",
    category: "Bilişsel & Kodlama",
    description: "Kelimelerin ilk ve son seslerini bulma, ilkokul okuma-yazma hazırlık egzersizleri.",
    instructor: "Ahmet Özdemir",
  },
  {
    id: "act-602",
    classId: 6,
    title: "Satranç Stratejisi: Şah & Vezir",
    time: "14:00 - 15:00",
    date: "Bugün",
    category: "Bilişsel & Kodlama",
    description: "Büyük satranç tahtasında taşların hareket mantığı ve hamle planlama.",
    instructor: "Ahmet Özdemir",
  },
];

export const INITIAL_MEDIA: MediaItem[] = [
  {
    id: "med-1",
    type: "image",
    url: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&auto=format&fit=crop&q=80",
    title: "Bahar Şenliği ve Açık Hava Oyunları",
    description: "Çocuklarımız kreşimizin yemyeşil bahçesinde doğanın tadını çıkarırken.",
    date: "2026-09-15",
    classId: null,
    isPublic: true,
    category: "Bahçe Oyunları",
  },
  {
    id: "med-2",
    type: "image",
    url: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&auto=format&fit=crop&q=80",
    title: "Minik Parmaklar Renkli Dünyalar",
    description: "2. Sınıf Kelebekler grubumuzun eğlenceli parmak boyama serüveni.",
    date: "2026-09-14",
    classId: 2,
    isPublic: true,
    category: "Sanat Atölyesi",
  },
  {
    id: "med-3",
    type: "image",
    url: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80",
    title: "Kitap Kurdu Masal Saati",
    description: "Masal köşemizde öğretmenimiz eşliğinde sihirli bir serüvene yolculuk.",
    date: "2026-09-12",
    classId: 3,
    isPublic: true,
    category: "Özel Günler",
  },
  {
    id: "med-4",
    type: "image",
    url: "https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=800&auto=format&fit=crop&q=80",
    title: "Minik Mucitler STEM Laboratuvarı",
    description: "4. Sınıf öğrencilerimiz fen deneyleriyle suyun kaldırma kuvvetini keşfediyor.",
    date: "2026-09-11",
    classId: 4,
    isPublic: true,
    category: "Doğa & Bilim",
  },
  {
    id: "med-5",
    type: "image",
    url: "https://images.unsplash.com/photo-1596464716127-f2a829822391?w=800&auto=format&fit=crop&q=80",
    title: "Masal Kahramanları Tiyatro Provası",
    description: "5. Sınıfımızın hazırladığı Orman Dostları tiyatro oyununun kostümlü provası.",
    date: "2026-09-10",
    classId: 5,
    isPublic: true,
    category: "Sanat Atölyesi",
  },
  {
    id: "med-6",
    type: "image",
    url: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&auto=format&fit=crop&q=80",
    title: "Geleceğin Yıldızları Mezuniyet Heyecanı",
    description: "6. Sınıf mezun adaylarımız kepleriyle ilkokula gururla adım atıyor.",
    date: "2026-09-08",
    classId: 6,
    isPublic: true,
    category: "Özel Günler",
  },
  {
    id: "med-7",
    type: "video",
    url: "https://assets.mixkit.co/videos/preview/mixkit-children-playing-with-plasticine-at-kindergarten-43309-large.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&auto=format&fit=crop&q=80",
    title: "Oyun Hamuru ve Heykel Sanatı Videosu",
    description: "Çocuklarımızın parmak kaslarını geliştiren renkli oyun hamuru çalışması anları.",
    date: "2026-09-15",
    classId: null,
    isPublic: true,
    category: "Sanat Atölyesi",
  },
  {
    id: "med-8",
    type: "video",
    url: "https://assets.mixkit.co/videos/preview/mixkit-kids-playing-in-a-kindergarten-classroom-43307-large.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&auto=format&fit=crop&q=80",
    title: "Kreşimizde Bir Gün - Tanıtım Filmi",
    description: "Masal Diyarı'nda neşe dolu sabah karşılamasından gün sonu oyunlarına renkli kesitler.",
    date: "2026-09-16",
    classId: null,
    isPublic: true,
    category: "Genel",
  },
];

export const INITIAL_MENU: MealMenuItem[] = [
  {
    day: "Pazartesi",
    breakfast: "Köy yumurtalı omlet, tulum peyniri, ev yapımı zeytin ezmesi, ıhlamur çayı, tam buğday ekmeği",
    lunch: "Süzme mercimek çorbası, fırında sebzeli köfte, bulgur pilavı, ev yapımı probiyotik yoğurt",
    snack: "Fırınlanmış tarçınlı elma dilimleri ve ceviz içi",
  },
  {
    day: "Salı",
    breakfast: "Organik yulaf lapası, taze muz ve böğürtlen parçaları, kaşar peyniri, ılık süt",
    lunch: "Tarhana çorbası, nohutlu taze köy tavuğu yahnisi, basmati pirinç pilavı, mevsim salatası",
    snack: "Ev yapımı havuçlu kek ve taze sıkılmış portakal suyu",
  },
  {
    day: "Çarşamba",
    breakfast: "Peynirli mini gül böreği, domates-salatalık söğüş, haşlanmış yumurta, taze nane çayı",
    lunch: "Balkabağı çorbası, ev yapımı kıymalı mantı, taze nane soslu yoğurt",
    snack: "Kuru kayısı, kuru incir ve kavrulmamış çiğ badem",
  },
  {
    day: "Perşembe",
    breakfast: "Menemen, lor peynirli taze yeşillikler, zeytin, kepekli tost ekmeği, açık papatya çayı",
    lunch: "Kremasız sebze çorbası, fırında somon balığı, fırın patates, limonlu yeşil salata",
    snack: "Ev yapımı muzlu puding (şekersiz, hurma özlü)",
  },
  {
    day: "Cuma",
    breakfast: "Pankek (organik un & yumurta), doğal çiçek balı, labne peyniri, ceviz, taze süt",
    lunch: "Şehriye çorbası, zeytinyağlı taze fasulye, arpa şehriyeli pirinç pilavı, cacık",
    snack: "Fırından yeni çıkmış simit ve taze tulum peyniri",
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-1",
    title: "🎉 Bahar Dönemi Masal Şenliği ve Sanat Sergisi",
    content: "Öğrencilerimizin yıl boyunca yaptığı kil heykeller ve tuval tabloları bu Cuma saat 15:00'te kreşimizin fuayesinde sergilenecektir. Tüm velilerimiz davetlidir!",
    date: "2026-09-15",
    important: true,
    targetAudience: "tumu",
  },
  {
    id: "ann-2",
    title: "🦷 Çocuk Diş Hekimi Kontrolü & Sağlık Taraması",
    content: "Pazartesi günü anlaşmalı uzman pedodontistimiz tüm sınıflarımızda minik diş kontrolü gerçekleştirecektir. Raporlar veli sistemine yüklenecektir.",
    date: "2026-09-14",
    important: false,
    targetAudience: "veliler",
  },
  {
    id: "ann-3",
    title: "🌿 4 ve 5. Sınıflar Botanik Park Gezisi",
    content: "Minik Mucitler ve Masal Kahramanları sınıflarımız Çarşamba günü Atatürk Arboretumu'nda doğa keşfinde olacaklardır. Lütfen rahat spor ayakkabı giydiriniz.",
    date: "2026-09-13",
    important: true,
    targetAudience: "veliler",
  },
];

export const INITIAL_APPLICATIONS: RegistrationApplication[] = [
  {
    id: "app-1",
    parentName: "Ayşe Yücel",
    parentPhone: "0532 999 11 22",
    parentEmail: "ayse.yucel@example.com",
    childName: "Deniz Yücel",
    childAge: "3 Yaş",
    preferredClassId: 3,
    notes: "Tam gün program istiyoruz. Servis imkanı var mı?",
    createdAt: "2026-09-16 14:20",
    status: "beklemede",
  },
  {
    id: "app-2",
    parentName: "Tolga Erdem",
    parentPhone: "0542 888 77 66",
    parentEmail: "tolga.erdem@example.com",
    childName: "Melis Erdem",
    childAge: "4 Yaş",
    preferredClassId: 4,
    notes: "Montessori ağırlıklı sınıfınız için görüşmek istiyoruz.",
    createdAt: "2026-09-15 18:45",
    status: "arandi",
  },
];

export const ACADEMIC_MONTHS = [
  "Eylül 2026",
  "Ekim 2026",
  "Kasım 2026",
  "Aralık 2026",
  "Ocak 2027",
  "Şubat 2027",
  "Mart 2027",
  "Nisan 2027",
  "Mayıs 2027",
  "Haziran 2027",
];

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: "tch-1",
    classId: 1,
    name: "Merve Güneş",
    title: "Bebek & Erken Çocukluk Gelişim Uzmanı",
    username: "ogretmen1",
    password: "1234",
    phone: "0532 101 00 01",
    email: "merve.gunes@masaldiyari.k12.tr",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "tch-2",
    classId: 2,
    name: "Zeynep Çelik",
    title: "Çocuk Gelişimi & Montessori Eğitmeni",
    username: "ogretmen2",
    password: "1234",
    phone: "0532 101 00 02",
    email: "zeynep.celik@masaldiyari.k12.tr",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "tch-3",
    classId: 3,
    name: "Elif Doğan",
    title: "Okul Öncesi Öğretmeni & Doğa Pedagoğu",
    username: "ogretmen3",
    password: "1234",
    phone: "0532 101 00 03",
    email: "elif.dogan@masaldiyari.k12.tr",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "tch-4",
    classId: 4,
    name: "Selin Yılmaz",
    title: "Okul Öncesi STEM & Zeka Oyunları Eğitmeni",
    username: "ogretmen4",
    password: "1234",
    phone: "0532 101 00 04",
    email: "selin.yilmaz@masaldiyari.k12.tr",
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "tch-5",
    classId: 5,
    name: "Gamze Karaca",
    title: "Sanat Eğitmeni & Masal Terapisti",
    username: "ogretmen5",
    password: "1234",
    phone: "0532 101 00 05",
    email: "gamze.karaca@masaldiyari.k12.tr",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "tch-6",
    classId: 6,
    name: "Ahmet Özdemir",
    title: "Kıdemli Okul Öncesi Eğitim Koordinatörü",
    username: "ogretmen6",
    password: "1234",
    phone: "0532 101 00 06",
    email: "ahmet.ozdemir@masaldiyari.k12.tr",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
];

// Helper to generate initial 10-month dues for all initial students
const generateInitialDues = (): MonthlyDue[] => {
  const dues: MonthlyDue[] = [];
  const monthDueDates = [
    "2026-09-05",
    "2026-10-05",
    "2026-11-05",
    "2026-12-05",
    "2027-01-05",
    "2027-02-05",
    "2027-03-05",
    "2027-04-05",
    "2027-05-05",
    "2027-06-05",
  ];

  INITIAL_STUDENTS.forEach((student) => {
    ACADEMIC_MONTHS.forEach((monthName, idx) => {
      const monthIndex = idx + 1;
      const dueDate = monthDueDates[idx];
      const dueId = `due-${student.id}-${monthIndex}`;
      let status: "odendi" | "odenmedi" | "beklemede" = "odenmedi";
      let paidDate: string | undefined = undefined;
      let paymentMethod: "Havale / EFT" | "Kredi Kartı" | "Nakit" | undefined = undefined;
      let receiptNo: string | undefined = undefined;
      let notes: string | undefined = undefined;

      // Realistic mock statuses
      if (monthIndex === 1) {
        // September (current month): most paid, 1 pending, 1 unpaid
        if (student.id === "stu-202") {
          status = "beklemede";
          notes = "Veli havale dekontu gönderecek";
        } else if (student.id === "stu-602") {
          status = "odenmedi";
          notes = "Gecikmede - Hatırlatma SMS'i iletildi";
        } else {
          status = "odendi";
          paidDate = `2026-09-0${(parseInt(student.id.replace(/\D/g, "")) % 4) + 1}`;
          paymentMethod = idx % 2 === 0 ? "Havale / EFT" : "Kredi Kartı";
          receiptNo = `MAK-2026-09-${student.id.replace("stu-", "")}`;
          notes = "Eylül aidatı zamanında tahsil edildi";
        }
      } else if (monthIndex === 2) {
        // October: a few early payers
        if (student.id === "stu-101" || student.id === "stu-301" || student.id === "stu-501") {
          status = "odendi";
          paidDate = "2026-09-15";
          paymentMethod = "Havale / EFT";
          receiptNo = `MAK-2026-10-${student.id.replace("stu-", "")}`;
          notes = "Erken dönem peşin ödendi";
        } else if (student.id === "stu-102") {
          status = "beklemede";
          notes = "Kredi kartı otomatik talimatında";
        } else {
          status = "odenmedi";
        }
      } else {
        // Months 3 to 10: upcoming
        status = "odenmedi";
      }

      dues.push({
        id: dueId,
        studentId: student.id,
        classId: student.classId,
        month: monthName,
        monthIndex,
        amount: 12500, // 12.500 TL
        status,
        dueDate,
        paidDate,
        paymentMethod,
        receiptNo,
        notes,
      });
    });
  });

  return dues;
};

export const INITIAL_DUES: MonthlyDue[] = generateInitialDues();
